### ISSUE TITLE
Pause mark collisions

### ISSUE THREAD

**Issue by mustafa0x** [quranacademy/kitab-font#1]
# یَـٰۤـَٔادَمُ
# عَلَّمۡتَنَاۤۖ
# قَامُواۚ
# بَلَىٰۤۚ
# تَعۡدِلُوا۟ۚ
# تَلۡوُۥۤا۟
# دَاۤبَّةࣲ
# أَهَـٰۤؤُلَاۤءِ
# بَیۡنِنَاۤۗ
# بِهِۦۤۚ
# لِلَّهِۖ
# حَسۡبُهُۥۤۚ
# سِیۤـَٔتۡ
# نۤۚ
# هَنِیۤـَٔۢا
# كَلَّاۤۖ
# صَفࣰّاۖ
# فِیهَاۤۚ
# وَلِـِّۧیَ
# وَٱسۡمَعُوا۟ۖ
# أَشۡرَكُوا۟ۚ
# جَزَاۤؤُهُمۡ (near collision)

---

# یُحۡـِۧیَ

---

# مَّرۡقَدِنَاۜۗ
# بَصۜۡطَةࣰۖ
# وَیَبۡصُۜطُ

---

لَلۡـَٔاخِرَةَ (this should use the لا ligature)

**Comment by mustafa0x** [comment]
أَشۡرَكُوا۟ۗ
بَیۡنَهُمَاۤۗ
بَیۡنِنَاۤۗ
بِأَمۡرِهِۦۤۗ
بِهِۦۤۗ
تَضِلُّوا۟ۗ
تَهۡتَدُوا۟ۗ
تُحۡصُوهَاۤۗ
جِنَّةُۢۗ
رَحۡمَتِهِۦۤۗ
رَّبِّهِۦۤۗ
رُدُّوهَاۤۗ
سَوَاۤءࣰۗ
شَجَرَهَاۤۗ
عَنۡهُمَاۤۗ
فِیهَاۤۗ
قُتِلُوا۟ۗ
قُرۡبَىٰۤۗ
لِلَّهِۗ
مَّرۡقَدِنَاۜۗ
مِثۡلِهَاۤۗ
مِنۡهَاۤۗ
ٱسۡتَكَانُوا۟ۗ
ٱصۡطَفَىٰۤۗ
ٱللَّهِۗ
ٱلۡقُرَىٰۤۗ
یَحۡبِسُهُۥۤۗ
یَشَاۤءُۗ

---


ءَابَاۤؤُكُمۡۖ
أَحۡیَاۤءࣲۖ
أَهۡلَكۡنَـٰهَاۤۖ
بَعۡدِیۤۖ
بَیۡنَهُمَاۤۖ
بِتَأۡوِیلِهِۦۤۖ
بِرَأۡسِیۤۖ
بِـَٔایَـٰتِنَاۤۖ
بِهَاۤۖ
بِٱلۡفَحۡشَاۤءِۖ
تَحۡزَنِیۤۖ
تَخَافَاۤۖ
تُقَـٰتِلُوا۟ۖ
حَـٰفِظࣰاۖ
حَفِیظࣰاۖ
حَقࣰّاۖ
دَكَّاۤءَۖ
رَبِّنَاۤۖ
رَبِّیۤۖ
رَحۡمَتِنَاۤۖ
سَوَاۤءࣲۖ
شُرَكَاۤءَۖ
صَدَقُوا۟ۖ
ضَیۡفِیۤۖ
عَـٰهَدُوا۟ۖ
عَلَیۡنَاۤۖ
غَیۡرُهُۥۤۖ
قَبۡرِهِۦۤۖ
كَسَبُوا۟ۖ
كَلَّاۤۖ
لَنَاۤۖ
لِلَّهِۖ
مَكَانَهُۥۤۖ
مَّاۤءࣲۖ
مِنَّاۤۖ
مِنِّیۤۖ
نَفۡسِیۤۖ
هَـٰذَاۤۖ
ٱدۡفَعُوا۟ۖ
ٱكۡتَسَبُوا۟ۖ
ٱلزِّنَىٰۤۖ
ٱلسَّمَاۤءِۖ
ٱللَّهَۖ
ٱللَّهِۖ
ٱلنِّسَاۤءِۖ
ٱلۡأَمۡرِۖ
ٱلۡأَهِلَّةِۖ
ٱلۡقِطۡرِۖ
ٱهۡتَدَوا۟ۖ
یُصَدِّقُنِیۤۖ

---

ءَابَاۤءَنَاۤۚ
ءَایَـٰتِنَاۤۚ
ءَایَـٰتِهِۦۤۚ
الۤرۚ
أَحۡسَنَهُۥۤۚ
أَرۡضِنَاۤۚ
أَشۡرَكُوا۟ۚ
أَطۡرَافِهَاۤۚ
أَعۡمَىٰۤۚ
أَلۡوَ ٰ⁠نُهُۥۤۚ
أَمۡوَ ٰ⁠تُۢۚ
أَوۡلِیَاۤءَهُۥۤۚ
إِخۡوَتِیۤۚ
بَعۡدِهِۦۤۚ
بَلَىٰۤۚ
بِأَمۡرِهِۦۤۚ
بِإِذۡنِهِۦۤۚ
بِـَٔایَـٰتِنَاۤۚ
بِـَٔایَـٰتِهِۦۤۚ
بِنَاصِیَتِهَاۤۚ
بِهَاۤۚ
بِهَـٰذَاۤۚ
بِهِۦۤۚ
تَعۡتَدُوۤا۟ۚ
تَعۡدِلُوا۟ۚ
تَغۡتَسِلُوا۟ۚ
تَفَرَّقُوا۟ۚ
تَفۡتِنِّیۤۚ
تُطِعۡهُمَاۤۚ
جَاۤءَهُۥۤۚ
جِنَّةُۢۚ
خَرَابِهَاۤۚ
خَلَقۡنَاۤۚ
دُعُوا۟ۚ
رَبِّیۤۚ
رَحۡمَتِهِۦۤۚ
رُسُلَهُۥۤۚ
زَوۡجَهُۥۤۚ
سَبِیلِهِۦۤۚ
سَوۡءَ ٰ⁠ تِهِمَاۤۚ
سُبۡحَـٰنَهُۥۤۚ
شَهِدۡنَاۤۚ
صۤۚ
طسۤۚ
عَدُوُّۢۚ
عَذَابَهُۥۤۚ
عَلَیۡنَاۤۚ
عَنِّیۤۚ
عَنۡهَاۤۚ
عِندِیۤۚ
غَیۡرُهُۥۤۚ
غُلۡفُۢۚ
فَتَبَیَّنُوۤا۟ۚ
فَضۡلِهِۦۤۚ
فَطَرَنِیۤۚ
قَبۡلِهِۦۤۚ
قَدۡرِهِۦۤۚ
كَسَبُوا۟ۚ
كَسَبُوۤا۟ۚ
كَفَرُوا۟ۚ
كَفَرُوۤا۟ۚ
كَلَّاۤۚ
كُفۡرُهُۥۤۚ
لَهُۥۤۚ
لِنَفۡسِهِۦۤۚ
لِّتَعۡتَدُوا۟ۚ
مَوۡتِهَاۤۚ
مُوسَىٰۤۚ
نَافَقُوا۟ۚ
نَفۡسِیۤۚ
وَأَبۡقَىٰۤۚ
وَأَحۡسِنُوۤا۟ۚ
وَبَاطِنَهُۥۤۚ
وَرَسُولَهُۥۤۚ
وَقَوۡمِهِۦۤۚ
وَمَلَإِی۟هِۦۤۚ
وَمُرۡسَىٰهَاۤۚ
وَٱجۡتَبَیۡنَاۤۚ
وَیَنۡعِهِۦۤۚ
ٱسۡتَطَـٰعُوا۟ۚ
ٱلرُّءۡیَاۤۚ
ٱلرِّبَوٰا۟ۚ
یَصَّدَّقُوا۟ۚ
یَكۡبَرُوا۟ۚ
یَنصُرُهُۥۤۚ
یُبَدِّلُونَهُۥۤۚ
یُعِیدُهُۥۤۚ
یُؤۡمِنُوا۟ۚ

---

ءَابَاۤؤُهُمۡ
ءَامَنُوا۟ۘ
أَوۡلِیَاۤءَۘ
أَوۡلِیَاۤؤُهُمُ
تَلۡوُۥۤا۟
جَزَاۤؤُهُم
جَزَ ٰ⁠ۤؤُا۟
دَاۤبَّةࣲ
رِبِّیُّونَ
فَأۡوُۥۤا۟
كَاۤفَّةࣰ
لِیَسُـࣳۤـُٔوا۟
نِسَاۤؤُكُمۡ
وَلِـِّۧیَ
وَیَبۡصُۜطُ
ٱلضَّاۤلُّونَ

**Comment by khaledhosny** [comment]
These should be fixed now, except for the following words:
حَـٰفِظࣰاۖ
حَفِیظࣰاۖ
حَقࣰّاۖ
ٱللَّهِۗ
سَوَاۤءࣰۗ
لِلَّهِۗ
سَوَاۤءࣲۖ
لِلَّهِۖ
ٱللَّهَۖ
ٱللَّهِۖ
ٱلۡأَمۡرِۖ
ٱلۡأَهِلَّةِۖ
ٱلۡقِطۡرِۖ
الۤرۚ

I will have to figure out what is the best solution for these.

**Comment by mustafa0x** [comment]
Wonderful work.

لَلۡـَٔاخِرَةَ (this should use the لا ligature)

Remaining collisions:
الۤرۚ
حَـٰفِظࣰاۖ
حَفِیظࣰاۖ
حَقࣰّاۖ
لِلَّهِۖ
ٱللَّهِۖ
ٱلۡأَهِلَّةِۖ
ٱلۡقِطۡرِۖ
صَفࣰّاۖ
سَوَاۤءࣲۖ
جَزَ ٰ⁠ۤؤُا۟

Regressions:
هَنِیۤـَٔۢا

Near collisions:
ٱلۡأَمۡرِۖ
ٱللَّهَۖ
ٱللَّهِۗ
سَوَاۤءࣰۗ
جَزَاۤؤُهُمۡ
یُحۡـِۧیَ
ٱلسَّمَاۤءِۖ
ٱلنِّسَاۤءِۖ
مَكَانَهُۥۤۖ
مَّاۤءࣲۖ
غَیۡرُهُۥۤۖ
سَوۡءَ ٰ⁠ تِهِمَاۤۚ (the small alif)
جَزَاۤؤُهُم
دَاۤبَّةࣲ
رِبِّیُّونَ
