### ISSUE TITLE
Allow special dammatan, fathatan and kathratan for tajweed cases

### ISSUE THREAD

**Issue by Ysajid** [quranacademy/kitab-font#10]
For tajweed, in Madani mushaf a special form of dammatan, fathatan and kathratan is used. The case is handled in me quran and KFGQPC Uthmanic hafs font by using font ligture. Can that also be implemented in kitab font?

The special characters' unicodes are:
1. dammatan (`u065e`)
2. fathatan (`u0657`)
3. kathratan (`u0656`)

The font ligture combinations
1. dammatan (`u064c u06ed`)
2. fathatan (`﻿u064b u0659`)
3. kathratan (`u064d u06e2`)

releted issue https://gitlab.com/greentech/quran/Quranfiles/-/issues/91

**Comment by mustafa0x** [comment]
That approach is incorrect; see [Quran-text](https://github.com/quranacademy/quran-text) for the proper approach:

> Use open Tanween (U+08F0, U+08F1, U+08F2) in ikhfaa and idghaam cases, instead of regular Tanween (U+064B, U+064C, U+064D).

**Comment by Ysajid** [comment]
Jajhakallahu khairan @mustafa0x

**Comment by Ysajid** [comment]
One concern is that, won't it create compatibility issues with other fonts (KFGQPC hafs, Me Quran etc.)?

**Comment by mustafa0x** [comment]
وإياكم

> won't it create compatibility issues

Custom ligatures isn't a matter where compatibility is a goal. Unicode compliancy is.

The Quran text linked to above remains (mostly) the same as long as there is Unicode support, while QPC's text breaks when copying and pasting (e.g. as a message on social media).

**Comment by Ysajid** [comment]
> Custom ligatures isn't a matter where compatibility is a goal. Unicode compliancy is.
> The Quran text linked to above remains (mostly) the same as long as there is Unicode support, while QPC's text breaks when copying and pasting (e.g. as a message on social media).  

Understood.
