### ISSUE TITLE
Punctuation is too tight 

### ISSUE THREAD

**Issue by vipafattal** [quranacademy/kitab-font#13]
I'm using Kitab font bold with [this](https://raw.githubusercontent.com/quranacademy/quran-text/master/quran-uthmani.txt) text version to render Quran on the native android platform.

There are multiple occasions where the punctuation is too tight for example

![image](https://user-images.githubusercontent.com/22567094/167461422-0c902b25-21b4-41ed-9626-9d2cebaa7cd4.png)

 
![image](https://user-images.githubusercontent.com/22567094/167461691-594853d0-50e1-46ad-ad18-b63979b900b5.png)

**Comment by mustafa0x** [comment]
Thank you for the feedback.

Unfortunately this is a known issue; see #6. Feel free to add any occurrences we're missing to it.

Hopefully within a few months Dr khaled hosny and I will work on them.
