### ISSUE TITLE
I couldn't use this font in my web project

### ISSUE THREAD

**Issue by WatheqAlshowaiter** [quranacademy/kitab-font#14]
I use the convention in my CSS file

```
@font-face {
            font-family: 'Kitab';
            src: 'path/to/font/Kitab-Regular.ttf'
        }
```

forgive me if my question is silly but I tried to use the awesome but I couldn't. Usually I apply the technique above to change fonts in my web projects.

**Comment by mustafa0x** [comment]
Did you add `font-family: 'Kitab';` to `body {}` or another selector?

**Comment by WatheqAlshowaiter** [comment]
Yes. but the font not changed.

**Comment by mustafa0x** [comment]
I'm not sure what you might be doing. Share a link and I'll try to take a quick look.

For reference here is a simple example: https://codepen.io/mustafa0x/pen/KKQXJRM
