### ISSUE TITLE
Italic/slanted variant

### ISSUE THREAD

**Issue by amarz45** [quranacademy/kitab-font#17]
Hello, it would be great if this font had an italic/slanted variant. That way, I wouldn't have to fake italics in LaTeX. Can you implement this like in Amiri? Thank you.

**Comment by mustafa0x** [comment]
Unfortunately, due to limited funding and other priorities, this is unlikely to happen any time soon.

Thank you for your interest. :)

**Comment by amarz45** [comment]
I hope this font gets the funding it deserves. Side note: When do you think the collision issues will be fixed? I noticed a lot of collisions when typesetting the Quran.

**Comment by mustafa0x** [comment]
I do as well! Perhaps a kickstarter-like initiative should be launched. It would at least require $5-10k.

I don't know. We fixed the major ones, but there still are a few with pause marks. If funding presents itself perhaps I can discuss with Khaled.

**Comment by amarz45** [comment]
This and Amiri are my favourite Arabic fonts. I would be happy to make a small donation and tell other people about the font to improve its development.
