### ISSUE TITLE
2 symbols not showing correctly

### ISSUE THREAD

**Issue by Muhammadibn** [quranacademy/kitab-font#3]
Assalamu 'alaykum 

A wonderful font. I like the fact that the honourifics have been added too as symbols. 

I was testing out صلى الله عليه وسلم and that comes full rather than the symbol. Additionally, جل جلاله also has the same problem and the word Allah too.

Please take a look at that.

Allah reward your efforts.

**Comment by mustafa0x** [comment]
وعليكم السلام ورحمة الله

The text isn't replaced automatically, you have to use that specific character. They can easily be copied from: https://nuqayah.com/tools/text.html

(I hope to soon update that tool to add the new honorifics).

**Comment by Muhammadibn** [comment]
Ah, I see, I was using the glyphs panel in Illustrator and it inserted the other symbols automatically so was expecting this to happen that way too. Copying from the website works Alhamdulillah.

Jazakallah for the fast response :)
