### ISSUE TITLE
Wrong ligature when using Kitab-bold

### ISSUE THREAD

**Issue by vipafattal** [quranacademy/kitab-font#7]
Thanks for this amazing font, but I'm having some issues in ligature (Arabic connected characters) when using `kitab_bold` in a Quran app for Android (Android Native), I'm attaching some screenshots in google drive link to show some samples of the issues [images](https://drive.google.com/drive/folders/1peOHYmtanfDrITPtXapubJifpZ9EFf_C?usp=sharing).
It worth mentioning that I've been using your other font `amiri-bold` in the same place and didn't show any of these errors.

**Comment by mustafa0x** [comment]
Use https://github.com/quranacademy/quran-text, not tanzil's uthmani text.
